// Auto-generated by: supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/database.types.ts
// Run this after setting up your Supabase project to get fully typed queries.
// For now this is a manual stub that matches our schema.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          username: string
          display_name: string
          avatar_url: string | null
          joined_at: string
          recos_sent: number
        }
        Insert: {
          id: string
          username: string
          display_name: string
          avatar_url?: string | null
          joined_at?: string
          recos_sent?: number
        }
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      friend_connections: {
        Row: {
          id: string
          user_id: string
          friend_id: string
          tier: 'band' | 'close' | 'clan' | 'tribe'
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['friend_connections']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['friend_connections']['Insert']>
      }
      recommendations: {
        Row: {
          id: string
          sender_id: string
          category: string
          custom_cat: string | null
          title: string
          why_text: string | null
          why_audio_url: string | null
          meta: Json
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['recommendations']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['recommendations']['Insert']>
      }
      reco_recipients: {
        Row: {
          id: string
          reco_id: string
          recipient_id: string
          status: 'unseen' | 'done'
          score: number | null
          feedback_text: string | null
          feedback_audio: string | null
          rated_at: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['reco_recipients']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['reco_recipients']['Insert']>
      }
      sin_bin: {
        Row: {
          id: string
          sender_id: string
          recipient_id: string
          category: string
          bad_count: number
          is_active: boolean
          triggered_at: string | null
          released_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['sin_bin']['Row'], 'id'>
        Update: Partial<Database['public']['Tables']['sin_bin']['Insert']>
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: 'feedback_received' | 'reco_received' | 'request_received' | 'friend_added' | 'sin_bin'
          actor_id: string
          reco_id: string | null
          read: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['notifications']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['notifications']['Insert']>
      }
      messages: {
        Row: {
          id: string
          reco_id: string
          sender_id: string
          recipient_id: string
          body: string | null
          audio_url: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['messages']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['messages']['Insert']>
      }
      reco_requests: {
        Row: {
          id: string
          requester_id: string
          target_id: string
          category: string | null
          context: string | null
          fulfilled: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['reco_requests']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['reco_requests']['Insert']>
      }
      lists: {
        Row: {
          id: string
          owner_id: string
          title: string
          description: string | null
          status: 'draft' | 'published'
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['lists']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['lists']['Insert']>
      }
      list_items: {
        Row: {
          id: string
          list_id: string
          category: string
          title: string
          note: string | null
          sort_order: number
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['list_items']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['list_items']['Insert']>
      }
      list_shares: {
        Row: {
          id: string
          list_id: string
          shared_with: string
          shared_at: string
          viewed: boolean
        }
        Insert: Omit<Database['public']['Tables']['list_shares']['Row'], 'id' | 'shared_at'>
        Update: Partial<Database['public']['Tables']['list_shares']['Insert']>
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
